default:
	git clone https://github.com/stackgl/webgl-workshop.git
	sudo cp -R webgl-workshop/workshop /usr/local/lib/node_modules/webgl-workshop/node_modules/@workshop
	sudo cp -R webgl-workshop/exercises /usr/local/lib/node_modules/webgl-workshop/node_modules/@exercise
	rm -rf webgl-workshop

.PHONY: default
